//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HV_DK_KhoaHoc
    {
        public int IDKhoaHoc { get; set; }
        public string MaHV { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string ChiTiet { get; set; }
    }
}
