//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public int ID { get; set; }
        public int IDNoiDungKH { get; set; }
        public string TenLop { get; set; }
        public Nullable<int> SoHV { get; set; }
        public string MaGV { get; set; }
    }
}
