//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTTinHocEntities : DbContext
    {
        public TTTinHocEntities()
            : base("name=TTTinHocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_TKB> CT_TKB { get; set; }
        public virtual DbSet<GV> GVs { get; set; }
        public virtual DbSet<HV> HVs { get; set; }
        public virtual DbSet<HV_DK_KhoaHoc> HV_DK_KhoaHoc { get; set; }
        public virtual DbSet<HV_Lop> HV_Lop { get; set; }
        public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<NoiDungKH> NoiDungKHs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TKB> TKBs { get; set; }
    }
}
