//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDungKH
    {
        public int ID { get; set; }
        public int IDKH { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
    }
}
