//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public int ID { get; set; }
        public string TenPhong { get; set; }
        public string Mota { get; set; }
    }
}
