//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Nhom5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> Quyen { get; set; }
        public string MaUser { get; set; }
    }
}
